server:
  port: 9090
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/v1/bills/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/parcial
      client:
        provider:
          client-parcial-gateway-provider:
            issuer-uri: http://localhost:8080/realms/parcial
        registration:
          client-parcial-gateway:
            provider: keycloak-provider
            client-id: api-gateway-client
            client-secret: sj5UstrXIynl3Y7pHbxGovQYOMReX8Ex
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak